name: GitHub CI

on:
  pull_request:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker build notary-builder --tag notary:builder
          tag="$(docker run --rm notary:builder sh -c 'echo $TAG' | awk '{gsub(/^v/, ""); print}')"
          docker tag notary:builder "notary:${tag}-builder"
      - run: docker build notary-server --tag notary:server
      - run: docker build notary-signer --tag notary:signer
      - uses: actions/checkout@v3 # clone Notary upstream repo (used for generating necessary certificates to test against)
        with:
          repository: 'notaryproject/notary'
          ref: '74ee191c214795fb5e839bca841c7be2030d0002'
          path: 'notary-src'
      - run: NOTARY_SOURCE="$GITHUB_WORKSPACE/notary-src" ./.test/test.sh
