name: GitHub CI

on:
  pull_request:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build notary-server --tag notary:server
      - run: docker build notary-signer --tag notary:signer
      - uses: actions/checkout@v3 # clone Notary upstream repo (used for generating necessary certificates to test against)
        with:
          repository: 'notaryproject/notary'
          ref: '887a007da8841e49023684656926d79d89d5a9d8'
          path: 'notary-src'
      - run: NOTARY_SOURCE="$GITHUB_WORKSPACE/notary-src" ./.test/test.sh
